sample_response = [
    {
        '_links': {'award_emoji': 'https://gitlab.com/api/v4/projects/41272516/issues/1/award_emoji',
                   'closed_as_duplicate_of': None,
                   'notes': 'https://gitlab.com/api/v4/projects/41272516/issues/1/notes',
                   'project': 'https://gitlab.com/api/v4/projects/41272516',
                   'self': 'https://gitlab.com/api/v4/projects/41272516/issues/1'},
        'assignee': None,
        'assignees': [],
        'author': {'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                   'id': 12433373,
                   'name': 'Ilkka Väisänen',
                   'state': 'active',
                   'username': 'ivaisanen',
                   'web_url': 'https://gitlab.com/ivaisanen'},
        'blocking_issues_count': 0,
        'closed_at': None,
        'closed_by': None,
        'confidential': False,
        'created_at': '2022-11-22T13:27:56.554Z',
        'description': 'issue numero yksi sisältö ja liite '
        '[liite8.txt](/uploads/05a314ad019c8b3592733a5802f6c36a/liite8.txt)',
        'discussion_locked': None,
        'downvotes': 0,
        'due_date': None,
        'has_tasks': False,
        'id': 119188120,
        'iid': 1,
        'issue_type': 'issue',
        'labels': [],
        'merge_requests_count': 0,
        'milestone': None,
        'moved_to_id': None,
        'project_id': 41272516,
        'references': {'full': 'rasse-posse/scripting-testing-subgroup/second-scripting-testing-subgroup/scripting-testing-project-in-subgroup#1',
                       'relative': 'rasse-posse/scripting-testing-subgroup/second-scripting-testing-subgroup/scripting-testing-project-in-subgroup#1',
                       'short': '#1'},
        'service_desk_reply_to': None,
        'severity': 'UNKNOWN',
        'state': 'opened',
        'task_completion_status': {'completed_count': 0, 'count': 0},
        'time_stats': {'human_time_estimate': None,
                       'human_total_time_spent': None,
                       'time_estimate': 0,
                       'total_time_spent': 0},
        'title': 'issue numero yksi',
        'type': 'ISSUE',
        'updated_at': '2022-11-22T13:27:56.554Z',
        'upvotes': 0,
        'user_notes_count': 0,
        'web_url': 'https://gitlab.com/rasse-posse/scripting-testing-subgroup/second-scripting-testing-subgroup/scripting-testing-project-in-subgroup/-/issues/1'
    },
    {
        '_links': {'award_emoji': 'https://gitlab.com/api/v4/projects/37532449/issues/4/award_emoji',
                   'closed_as_duplicate_of': None,
                   'notes': 'https://gitlab.com/api/v4/projects/37532449/issues/4/notes',
                   'project': 'https://gitlab.com/api/v4/projects/37532449',
                   'self': 'https://gitlab.com/api/v4/projects/37532449/issues/4'},
        'assignee': None,
        'assignees': [],
        'author': {'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                   'id': 12433373,
                   'name': 'Ilkka Väisänen',
                   'state': 'active',
                   'username': 'ivaisanen',
                   'web_url': 'https://gitlab.com/ivaisanen'},
        'blocking_issues_count': 0,
        'closed_at': None,
        'closed_by': None,
        'confidential': False,
        'created_at': '2022-11-17T13:55:11.793Z',
        'description': 'Neljännen '
        'testi[liite4.txt](/uploads/461a6b47d039f377903dfc1a5282b731/liite4.txt) '
        'issuen teksti sisältö jfdfds',
        'discussion_locked': None,
        'downvotes': 0,
        'due_date': None,
        'has_tasks': False,
        'id': 118915969,
        'iid': 4,
        'issue_type': 'issue',
        'labels': [],
        'merge_requests_count': 0,
        'milestone': {'created_at': '2022-11-18T13:57:41.029Z',
                      'description': 'This is the best milestone ever!!!!!',
                      'due_date': '2022-11-24',
                      'expired': True,
                      'id': 2879765,
                      'iid': 1,
                      'project_id': 37532449,
                      'start_date': '2022-11-18',
                      'state': 'active',
                      'title': 'The Best Milestone',
                      'updated_at': '2022-11-18T13:57:41.029Z',
                      'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/milestones/1'},
        'moved_to_id': None,
        'project_id': 37532449,
        'references': {'full': 'rasse-posse/backend-for-jira#4',
                       'relative': 'backend-for-jira#4',
                       'short': '#4'},
        'service_desk_reply_to': None,
        'severity': 'UNKNOWN',
        'state': 'opened',
        'task_completion_status': {'completed_count': 0, 'count': 0},
        'time_stats': {'human_time_estimate': None,
                       'human_total_time_spent': None,
                       'time_estimate': 0,
                       'total_time_spent': 0},
        'title': 'Neljäs testi issue',
        'type': 'ISSUE',
        'updated_at': '2022-11-18T13:58:19.767Z',
        'upvotes': 0,
        'user_notes_count': 4,
        'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/4'
    },
    {
        '_links': {'award_emoji': 'https://gitlab.com/api/v4/projects/37532449/issues/3/award_emoji',
                   'closed_as_duplicate_of': None,
                   'notes': 'https://gitlab.com/api/v4/projects/37532449/issues/3/notes',
                   'project': 'https://gitlab.com/api/v4/projects/37532449',
                   'self': 'https://gitlab.com/api/v4/projects/37532449/issues/3'},
        'assignee': None,
        'assignees': [],
        'author': {'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                   'id': 12433373,
                   'name': 'Ilkka Väisänen',
                   'state': 'active',
                   'username': 'ivaisanen',
                   'web_url': 'https://gitlab.com/ivaisanen'},
        'blocking_issues_count': 0,
        'closed_at': None,
        'closed_by': None,
        'confidential': True,
        'created_at': '2022-11-16T11:37:57.371Z',
        'description': 'Kolmannen testi issuen description '
        '[liite3.txt](/uploads/2bf861ce8317222053be6321f2c89f75/liite3.txt)',
        'discussion_locked': None,
        'downvotes': 0,
        'due_date': None,
        'has_tasks': False,
        'id': 118824728,
        'iid': 3,
        'issue_type': 'issue',
        'labels': ['Testi_labeli3'],
        'merge_requests_count': 0,
        'milestone': {'created_at': '2022-11-18T13:57:41.029Z',
                      'description': 'This is the best milestone ever!!!!!',
                      'due_date': '2022-11-24',
                      'expired': True,
                      'id': 2879765,
                      'iid': 1,
                      'project_id': 37532449,
                      'start_date': '2022-11-18',
                      'state': 'active',
                      'title': 'The Best Milestone',
                      'updated_at': '2022-11-18T13:57:41.029Z',
                      'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/milestones/1'},
        'moved_to_id': None,
        'project_id': 37532449,
        'references': {'full': 'rasse-posse/backend-for-jira#3',
                       'relative': 'backend-for-jira#3',
                       'short': '#3'},
        'service_desk_reply_to': None,
        'severity': 'UNKNOWN',
        'state': 'opened',
        'task_completion_status': {'completed_count': 0, 'count': 0},
        'time_stats': {'human_time_estimate': None,
                       'human_total_time_spent': None,
                       'time_estimate': 0,
                       'total_time_spent': 0},
        'title': 'Kolmas testi issue',
        'type': 'ISSUE',
        'updated_at': '2022-11-18T13:58:27.189Z',
        'upvotes': 0,
        'user_notes_count': 45,
        'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/3'
    },
    {
        '_links': {'award_emoji': 'https://gitlab.com/api/v4/projects/37532449/issues/2/award_emoji',
                   'closed_as_duplicate_of': None,
                   'notes': 'https://gitlab.com/api/v4/projects/37532449/issues/2/notes',
                   'project': 'https://gitlab.com/api/v4/projects/37532449',
                   'self': 'https://gitlab.com/api/v4/projects/37532449/issues/2'},
        'assignee': None,
        'assignees': [],
        'author': {'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                   'id': 12433373,
                   'name': 'Ilkka Väisänen',
                   'state': 'active',
                   'username': 'ivaisanen',
                   'web_url': 'https://gitlab.com/ivaisanen'},
        'blocking_issues_count': 0,
        'closed_at': None,
        'closed_by': None,
        'confidential': False,
        'created_at': '2022-11-16T11:36:48.251Z',
        'description': 'Toka testi issue description',
        'discussion_locked': None,
        'downvotes': 0,
        'due_date': None,
        'has_tasks': False,
        'id': 118824664,
        'iid': 2,
        'issue_type': 'issue',
        'labels': ['Testi_labeli2'],
        'merge_requests_count': 0,
        'milestone': {'created_at': '2022-11-18T13:57:41.029Z',
                      'description': 'This is the best milestone ever!!!!!',
                      'due_date': '2022-11-24',
                      'expired': True,
                      'id': 2879765,
                      'iid': 1,
                      'project_id': 37532449,
                      'start_date': '2022-11-18',
                      'state': 'active',
                      'title': 'The Best Milestone',
                      'updated_at': '2022-11-18T13:57:41.029Z',
                      'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/milestones/1'},
        'moved_to_id': None,
        'project_id': 37532449,
        'references': {'full': 'rasse-posse/backend-for-jira#2',
                       'relative': 'backend-for-jira#2',
                       'short': '#2'},
        'service_desk_reply_to': None,
        'severity': 'UNKNOWN',
        'state': 'opened',
        'task_completion_status': {'completed_count': 0, 'count': 0},
        'time_stats': {'human_time_estimate': None,
                       'human_total_time_spent': None,
                       'time_estimate': 0,
                       'total_time_spent': 0},
        'title': 'Toka Testi Issue',
        'type': 'ISSUE',
        'updated_at': '2022-11-18T13:58:35.530Z',
        'upvotes': 0,
        'user_notes_count': 0,
        'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/2'
    },
    {
        '_links': {'award_emoji': 'https://gitlab.com/api/v4/projects/37532449/issues/1/award_emoji',
                   'closed_as_duplicate_of': None,
                   'notes': 'https://gitlab.com/api/v4/projects/37532449/issues/1/notes',
                   'project': 'https://gitlab.com/api/v4/projects/37532449',
                   'self': 'https://gitlab.com/api/v4/projects/37532449/issues/1'},
        'assignee': {'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                     'id': 12433373,
                     'name': 'Ilkka Väisänen',
                     'state': 'active',
                     'username': 'ivaisanen',
                     'web_url': 'https://gitlab.com/ivaisanen'},
        'assignees': [{'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                       'id': 12433373,
                       'name': 'Ilkka Väisänen',
                       'state': 'active',
                       'username': 'ivaisanen',
                       'web_url': 'https://gitlab.com/ivaisanen'}],
        'author': {'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                   'id': 12433373,
                   'name': 'Ilkka Väisänen',
                   'state': 'active',
                   'username': 'ivaisanen',
                   'web_url': 'https://gitlab.com/ivaisanen'},
        'blocking_issues_count': 0,
        'closed_at': None,
        'closed_by': None,
        'confidential': False,
        'created_at': '2022-11-16T11:35:49.326Z',
        'description': 'Ekan testi issuen description '
        '[liite1.txt](/uploads/cce591fb40b8f4d26ca36193df2c2c28/liite1.txt)[liite2.txt](/uploads/9a89a909c37c2691db1aece8896708b7/liite2.txt)',
        'discussion_locked': None,
        'downvotes': 0,
        'due_date': '2022-11-17',
        'has_tasks': False,
        'id': 118824601,
        'iid': 1,
        'issue_type': 'issue',
        'labels': ['Testi_labeli1', 'Testi_labeli2', 'Testi_labeli3'],
        'merge_requests_count': 0,
        'milestone': {'created_at': '2022-11-18T13:57:41.029Z',
                      'description': 'This is the best milestone ever!!!!!',
                      'due_date': '2022-11-24',
                      'expired': True,
                      'id': 2879765,
                      'iid': 1,
                      'project_id': 37532449,
                      'start_date': '2022-11-18',
                      'state': 'active',
                      'title': 'The Best Milestone',
                      'updated_at': '2022-11-18T13:57:41.029Z',
                      'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/milestones/1'},
        'moved_to_id': None,
        'project_id': 37532449,
        'references': {'full': 'rasse-posse/backend-for-jira#1',
                       'relative': 'backend-for-jira#1',
                       'short': '#1'},
        'service_desk_reply_to': None,
        'severity': 'UNKNOWN',
        'state': 'opened',
        'task_completion_status': {'completed_count': 0, 'count': 0},
        'time_stats': {'human_time_estimate': None,
                       'human_total_time_spent': None,
                       'time_estimate': 0,
                       'total_time_spent': 0},
        'title': 'Eka testi issue',
        'type': 'ISSUE',
        'updated_at': '2022-11-18T13:58:11.254Z',
        'upvotes': 0,
        'user_notes_count': 0,
        'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/1'
    }
]

target_dict = [
    {
        'Assignee': None,
        'Author': 'ilkka.vaisanen@test.com',
        'Closed At (UTC)': None,
        'Comment Link': 'https://gitlab.com/api/v4/projects/41272516/issues/1/notes',
        'Created At (UTC)': '2022-11-22T13:27:56.554Z',
        'Description': 'issue numero yksi sisältö ja liite '
                        '[liite8.txt](/uploads/05a314ad019c8b3592733a5802f6c36a/liite8.txt)',
        'Due Date': None,
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/scripting-testing-subgroup/second-scripting-testing-subgroup/scripting-testing-project-in-subgroup/-/issues/1',
        'GitLab UID': 119188120,
        'Labels': [],
        'Milestone': 'The issue was not tied to a milestone',
        'Participant EP': 'https://gitlab.com/api/v4/projects/41272516/issues/1/participants',
        'State': 'opened',
        'Time Estimate': 0,
        'Time Spent': 0,
        'Title': 'issue numero yksi',
        'URL': 'https://gitlab.com/rasse-posse/scripting-testing-subgroup/second-scripting-testing-subgroup/scripting-testing-project-in-subgroup/-/issues/1'
    },
    {
        'Assignee': None,
        'Author': 'ilkka.vaisanen@test.com',
        'Closed At (UTC)': None,
        'Comment Link': 'https://gitlab.com/api/v4/projects/37532449/issues/4/notes',
        'Created At (UTC)': '2022-11-17T13:55:11.793Z',
        'Description': 'Neljännen '
                        'testi[liite4.txt](/uploads/461a6b47d039f377903dfc1a5282b731/liite4.txt) '
                        'issuen teksti sisältö jfdfds',
        'Due Date': None,
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/4',
        'GitLab UID': 118915969,
        'Labels': [],
        'Milestone': 'The Best Milestone',
        'Participant EP': 'https://gitlab.com/api/v4/projects/37532449/issues/4/participants',
        'State': 'opened',
        'Time Estimate': 0,
        'Time Spent': 0,
        'Title': 'Neljäs testi issue',
        'URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/4'
    },
    {
        'Assignee': None,
        'Author': 'ilkka.vaisanen@test.com',
        'Closed At (UTC)': None,
        'Comment Link': 'https://gitlab.com/api/v4/projects/37532449/issues/3/notes',
        'Created At (UTC)': '2022-11-16T11:37:57.371Z',
        'Description': 'Kolmannen testi issuen description '
                        '[liite3.txt](/uploads/2bf861ce8317222053be6321f2c89f75/liite3.txt)',
        'Due Date': None,
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/3',
        'GitLab UID': 118824728,
        'Labels': ['Testi_labeli3'],
        'Milestone': 'The Best Milestone',
        'Participant EP': 'https://gitlab.com/api/v4/projects/37532449/issues/3/participants',
        'State': 'opened',
        'Time Estimate': 0,
        'Time Spent': 0,
        'Title': 'Kolmas testi issue',
        'URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/3'
    },
    {
        'Assignee': None,
        'Author': 'ilkka.vaisanen@test.com',
        'Closed At (UTC)': None,
        'Comment Link': 'https://gitlab.com/api/v4/projects/37532449/issues/2/notes',
        'Created At (UTC)': '2022-11-16T11:36:48.251Z',
        'Description': 'Toka testi issue description',
        'Due Date': None,
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/2',
        'GitLab UID': 118824664,
        'Labels': ['Testi_labeli2'],
        'Milestone': 'The Best Milestone',
        'Participant EP': 'https://gitlab.com/api/v4/projects/37532449/issues/2/participants',
        'State': 'opened',
        'Time Estimate': 0,
        'Time Spent': 0,
        'Title': 'Toka Testi Issue',
        'URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/2'
    },
    {
        'Assignee': 'ilkka.vaisanen@test.com',
        'Author': 'ilkka.vaisanen@test.com',
        'Closed At (UTC)': None,
        'Comment Link': 'https://gitlab.com/api/v4/projects/37532449/issues/1/notes',
        'Created At (UTC)': '2022-11-16T11:35:49.326Z',
        'Description': 'Ekan testi issuen description '
                        '[liite1.txt](/uploads/cce591fb40b8f4d26ca36193df2c2c28/liite1.txt)[liite2.txt](/uploads/9a89a909c37c2691db1aece8896708b7/liite2.txt)',
        'Due Date': '2022-11-17',
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/1',
        'GitLab UID': 118824601,
        'Labels': ['Testi_labeli1', 'Testi_labeli2', 'Testi_labeli3'],
        'Milestone': 'The Best Milestone',
        'Participant EP': 'https://gitlab.com/api/v4/projects/37532449/issues/1/participants',
        'State': 'opened',
        'Time Estimate': 0,
        'Time Spent': 0,
        'Title': 'Eka testi issue',
        'URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/1'
    }
]

comment_sample_response = [
    {
        'id': 1021952749,
        'type': None,
        'body': 'MAGNIFICENT TEST COMMENT',
        'attachment': None,
        'author': {
            'id': 11979333,
            'username': 'rjpalt',
            'name': 'Rasmus Paltschik',
            'state': 'active',
            'avatar_url': 'https://secure.gravatar.com/avatar/0c3297d169653dbb9b5658e535e04638?s=80&d=identicon',
            'web_url': 'https://gitlab.com/rjpalt'
        },
        'created_at': '2022-07-11T09:40:48.906Z',
        'updated_at': '2022-07-11T09:40:48.908Z',
        'system': True,
        'noteable_id': 111444664,
        'noteable_type': 'Issue',
        'resolvable': False,
        'confidential': False,
        'internal': False,
        'noteable_iid': 3,
        'commands_changes': {}
    }
]

participants_sample_response = [
    {
        'id': 11979333,
        'username': 'testonen',
        'name': 'Testy Testersson',
        'state': 'active',
        'avatar_url': 'https://secure.gravatar.com/avatar/0c3297d169653dbb9b5658e535e04638?s=80&d=identicon',
        'web_url': 'https://gitlab.com/rjpalt'
    }
]
