sample_response = [
    {
        '_links': {'award_emoji': 'https://gitlab.com/api/v4/projects/41272516/issues/1/award_emoji',
                   'closed_as_duplicate_of': None,
                   'notes': 'https://gitlab.com/api/v4/projects/41272516/issues/1/notes',
                   'project': 'https://gitlab.com/api/v4/projects/41272516',
                   'self': 'https://gitlab.com/api/v4/projects/41272516/issues/1'},
        'assignee': None,
        'assignees': [],
        'author': {'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                   'id': 12433373,
                   'name': 'Ilkka Väisänen',
                   'state': 'active',
                   'username': 'ivaisanen',
                   'web_url': 'https://gitlab.com/ivaisanen'},
        'blocking_issues_count': 0,
        'closed_at': None,
        'closed_by': None,
        'confidential': False,
        'created_at': '2022-11-22T13:27:56.554Z',
        'description': 'issue numero yksi sisältö ja liite '
        '[liite8.txt](/uploads/05a314ad019c8b3592733a5802f6c36a/liite8.txt)',
        'discussion_locked': None,
        'downvotes': 0,
        'due_date': None,
        'has_tasks': False,
        'id': 119188120,
        'iid': 1,
        'issue_type': 'issue',
        'labels': [],
        'merge_requests_count': 0,
        'milestone': None,
        'moved_to_id': None,
        'project_id': 41272516,
        'references': {'full': 'rasse-posse/scripting-testing-subgroup/second-scripting-testing-subgroup/scripting-testing-project-in-subgroup#1',
                       'relative': 'rasse-posse/scripting-testing-subgroup/second-scripting-testing-subgroup/scripting-testing-project-in-subgroup#1',
                       'short': '#1'},
        'service_desk_reply_to': None,
        'severity': 'UNKNOWN',
        'state': 'opened',
        'task_completion_status': {'completed_count': 0, 'count': 0},
        'time_stats': {'human_time_estimate': None,
                       'human_total_time_spent': None,
                       'time_estimate': 0,
                       'total_time_spent': 0},
        'title': 'issue numero yksi',
        'type': 'ISSUE',
        'updated_at': '2022-11-22T13:27:56.554Z',
        'upvotes': 0,
        'user_notes_count': 0,
        'web_url': 'https://gitlab.com/rasse-posse/scripting-testing-subgroup/second-scripting-testing-subgroup/scripting-testing-project-in-subgroup/-/issues/1'
    },
    {
        '_links': {'award_emoji': 'https://gitlab.com/api/v4/projects/37532449/issues/4/award_emoji',
                   'closed_as_duplicate_of': None,
                   'notes': 'https://gitlab.com/api/v4/projects/37532449/issues/4/notes',
                   'project': 'https://gitlab.com/api/v4/projects/37532449',
                   'self': 'https://gitlab.com/api/v4/projects/37532449/issues/4'},
        'assignee': None,
        'assignees': [],
        'author': {'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                   'id': 12433373,
                   'name': 'Ilkka Väisänen',
                   'state': 'active',
                   'username': 'ivaisanen',
                   'web_url': 'https://gitlab.com/ivaisanen'},
        'blocking_issues_count': 0,
        'closed_at': None,
        'closed_by': None,
        'confidential': False,
        'created_at': '2022-11-17T13:55:11.793Z',
        'description': 'Neljännen '
        'testi[liite4.txt](/uploads/461a6b47d039f377903dfc1a5282b731/liite4.txt) '
        'issuen teksti sisältö jfdfds',
        'discussion_locked': None,
        'downvotes': 0,
        'due_date': None,
        'has_tasks': False,
        'id': 118915969,
        'iid': 4,
        'issue_type': 'issue',
        'labels': [],
        'merge_requests_count': 0,
        'milestone': {'created_at': '2022-11-18T13:57:41.029Z',
                      'description': 'This is the best milestone ever!!!!!',
                      'due_date': '2022-11-24',
                      'expired': True,
                      'id': 2879765,
                      'iid': 1,
                      'project_id': 37532449,
                      'start_date': '2022-11-18',
                      'state': 'active',
                      'title': 'The Best Milestone',
                      'updated_at': '2022-11-18T13:57:41.029Z',
                      'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/milestones/1'},
        'moved_to_id': None,
        'project_id': 37532449,
        'references': {'full': 'rasse-posse/backend-for-jira#4',
                       'relative': 'backend-for-jira#4',
                       'short': '#4'},
        'service_desk_reply_to': None,
        'severity': 'UNKNOWN',
        'state': 'opened',
        'task_completion_status': {'completed_count': 0, 'count': 0},
        'time_stats': {'human_time_estimate': None,
                       'human_total_time_spent': None,
                       'time_estimate': 0,
                       'total_time_spent': 0},
        'title': 'Neljäs testi issue',
        'type': 'ISSUE',
        'updated_at': '2022-11-18T13:58:19.767Z',
        'upvotes': 0,
        'user_notes_count': 4,
        'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/4'
    },
    {
        '_links': {'award_emoji': 'https://gitlab.com/api/v4/projects/37532449/issues/3/award_emoji',
                   'closed_as_duplicate_of': None,
                   'notes': 'https://gitlab.com/api/v4/projects/37532449/issues/3/notes',
                   'project': 'https://gitlab.com/api/v4/projects/37532449',
                   'self': 'https://gitlab.com/api/v4/projects/37532449/issues/3'},
        'assignee': None,
        'assignees': [],
        'author': {'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                   'id': 12433373,
                   'name': 'Ilkka Väisänen',
                   'state': 'active',
                   'username': 'ivaisanen',
                   'web_url': 'https://gitlab.com/ivaisanen'},
        'blocking_issues_count': 0,
        'closed_at': None,
        'closed_by': None,
        'confidential': True,
        'created_at': '2022-11-16T11:37:57.371Z',
        'description': 'Kolmannen testi issuen description '
        '[liite3.txt](/uploads/2bf861ce8317222053be6321f2c89f75/liite3.txt)',
        'discussion_locked': None,
        'downvotes': 0,
        'due_date': None,
        'has_tasks': False,
        'id': 118824728,
        'iid': 3,
        'issue_type': 'issue',
        'labels': ['Testi_labeli3'],
        'merge_requests_count': 0,
        'milestone': {'created_at': '2022-11-18T13:57:41.029Z',
                      'description': 'This is the best milestone ever!!!!!',
                      'due_date': '2022-11-24',
                      'expired': True,
                      'id': 2879765,
                      'iid': 1,
                      'project_id': 37532449,
                      'start_date': '2022-11-18',
                      'state': 'active',
                      'title': 'The Best Milestone',
                      'updated_at': '2022-11-18T13:57:41.029Z',
                      'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/milestones/1'},
        'moved_to_id': None,
        'project_id': 37532449,
        'references': {'full': 'rasse-posse/backend-for-jira#3',
                       'relative': 'backend-for-jira#3',
                       'short': '#3'},
        'service_desk_reply_to': None,
        'severity': 'UNKNOWN',
        'state': 'opened',
        'task_completion_status': {'completed_count': 0, 'count': 0},
        'time_stats': {'human_time_estimate': None,
                       'human_total_time_spent': None,
                       'time_estimate': 0,
                       'total_time_spent': 0},
        'title': 'Kolmas testi issue',
        'type': 'ISSUE',
        'updated_at': '2022-11-18T13:58:27.189Z',
        'upvotes': 0,
        'user_notes_count': 45,
        'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/3'
    },
    {
        '_links': {'award_emoji': 'https://gitlab.com/api/v4/projects/37532449/issues/2/award_emoji',
                   'closed_as_duplicate_of': None,
                   'notes': 'https://gitlab.com/api/v4/projects/37532449/issues/2/notes',
                   'project': 'https://gitlab.com/api/v4/projects/37532449',
                   'self': 'https://gitlab.com/api/v4/projects/37532449/issues/2'},
        'assignee': None,
        'assignees': [],
        'author': {'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                   'id': 12433373,
                   'name': 'Ilkka Väisänen',
                   'state': 'active',
                   'username': 'ivaisanen',
                   'web_url': 'https://gitlab.com/ivaisanen'},
        'blocking_issues_count': 0,
        'closed_at': None,
        'closed_by': None,
        'confidential': False,
        'created_at': '2022-11-16T11:36:48.251Z',
        'description': 'Toka testi issue description',
        'discussion_locked': None,
        'downvotes': 0,
        'due_date': None,
        'has_tasks': False,
        'id': 118824664,
        'iid': 2,
        'issue_type': 'issue',
        'labels': ['Testi_labeli2'],
        'merge_requests_count': 0,
        'milestone': {'created_at': '2022-11-18T13:57:41.029Z',
                      'description': 'This is the best milestone ever!!!!!',
                      'due_date': '2022-11-24',
                      'expired': True,
                      'id': 2879765,
                      'iid': 1,
                      'project_id': 37532449,
                      'start_date': '2022-11-18',
                      'state': 'active',
                      'title': 'The Best Milestone',
                      'updated_at': '2022-11-18T13:57:41.029Z',
                      'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/milestones/1'},
        'moved_to_id': None,
        'project_id': 37532449,
        'references': {'full': 'rasse-posse/backend-for-jira#2',
                       'relative': 'backend-for-jira#2',
                       'short': '#2'},
        'service_desk_reply_to': None,
        'severity': 'UNKNOWN',
        'state': 'opened',
        'task_completion_status': {'completed_count': 0, 'count': 0},
        'time_stats': {'human_time_estimate': None,
                       'human_total_time_spent': None,
                       'time_estimate': 0,
                       'total_time_spent': 0},
        'title': 'Toka Testi Issue',
        'type': 'ISSUE',
        'updated_at': '2022-11-18T13:58:35.530Z',
        'upvotes': 0,
        'user_notes_count': 0,
        'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/2'
    },
    {
        '_links': {'award_emoji': 'https://gitlab.com/api/v4/projects/37532449/issues/1/award_emoji',
                   'closed_as_duplicate_of': None,
                   'notes': 'https://gitlab.com/api/v4/projects/37532449/issues/1/notes',
                   'project': 'https://gitlab.com/api/v4/projects/37532449',
                   'self': 'https://gitlab.com/api/v4/projects/37532449/issues/1'},
        'assignee': {'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                     'id': 12433373,
                     'name': 'Ilkka Väisänen',
                     'state': 'active',
                     'username': 'ivaisanen',
                     'web_url': 'https://gitlab.com/ivaisanen'},
        'assignees': [{'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                       'id': 12433373,
                       'name': 'Ilkka Väisänen',
                       'state': 'active',
                       'username': 'ivaisanen',
                       'web_url': 'https://gitlab.com/ivaisanen'}],
        'author': {'avatar_url': 'https://secure.gravatar.com/avatar/8050cf3e7e68c94afd61dd6fb8879b46?s=80&d=identicon',
                   'id': 12433373,
                   'name': 'Ilkka Väisänen',
                   'state': 'active',
                   'username': 'ivaisanen',
                   'web_url': 'https://gitlab.com/ivaisanen'},
        'blocking_issues_count': 0,
        'closed_at': None,
        'closed_by': None,
        'confidential': False,
        'created_at': '2022-11-16T11:35:49.326Z',
        'description': 'Ekan testi issuen description '
        '[liite1.txt](/uploads/cce591fb40b8f4d26ca36193df2c2c28/liite1.txt)[liite2.txt](/uploads/9a89a909c37c2691db1aece8896708b7/liite2.txt)',
        'discussion_locked': None,
        'downvotes': 0,
        'due_date': '2022-11-17',
        'has_tasks': False,
        'id': 118824601,
        'iid': 1,
        'issue_type': 'issue',
        'labels': ['Testi_labeli1', 'Testi_labeli2', 'Testi_labeli3'],
        'merge_requests_count': 0,
        'milestone': {'created_at': '2022-11-18T13:57:41.029Z',
                      'description': 'This is the best milestone ever!!!!!',
                      'due_date': '2022-11-24',
                      'expired': True,
                      'id': 2879765,
                      'iid': 1,
                      'project_id': 37532449,
                      'start_date': '2022-11-18',
                      'state': 'active',
                      'title': 'The Best Milestone',
                      'updated_at': '2022-11-18T13:57:41.029Z',
                      'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/milestones/1'},
        'moved_to_id': None,
        'project_id': 37532449,
        'references': {'full': 'rasse-posse/backend-for-jira#1',
                       'relative': 'backend-for-jira#1',
                       'short': '#1'},
        'service_desk_reply_to': None,
        'severity': 'UNKNOWN',
        'state': 'opened',
        'task_completion_status': {'completed_count': 0, 'count': 0},
        'time_stats': {'human_time_estimate': None,
                       'human_total_time_spent': None,
                       'time_estimate': 0,
                       'total_time_spent': 0},
        'title': 'Eka testi issue',
        'type': 'ISSUE',
        'updated_at': '2022-11-18T13:58:11.254Z',
        'upvotes': 0,
        'user_notes_count': 0,
        'web_url': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/1'
    }
]

target_dict = [
    {
        'Assignee': None,
        'Author': 'ilkka.vaisanen@test.com',
        'Closed At (UTC)': None,
        'Comment Link': 'https://gitlab.com/api/v4/projects/41272516/issues/1/notes',
        'Created At (UTC)': '2022-11-22T13:27:56.554Z',
        'Description': 'issue numero yksi sisältö ja liite '
                        '[liite8.txt](/uploads/05a314ad019c8b3592733a5802f6c36a/liite8.txt)',
        'Due Date': None,
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/scripting-testing-subgroup/second-scripting-testing-subgroup/scripting-testing-project-in-subgroup/-/issues/1',
        'GitLab UID': 119188120,
        'Labels': [],
        'Milestone': 'The issue was not tied to a milestone',
        'Participant EP': 'https://gitlab.com/api/v4/projects/41272516/issues/1/participants',
        'State': 'opened',
        'Time Estimate': 0,
        'Time Spent': 0,
        'Title': 'issue numero yksi',
        'URL': 'https://gitlab.com/rasse-posse/scripting-testing-subgroup/second-scripting-testing-subgroup/scripting-testing-project-in-subgroup/-/issues/1'
    },
    {
        'Assignee': None,
        'Author': 'ilkka.vaisanen@test.com',
        'Closed At (UTC)': None,
        'Comment Link': 'https://gitlab.com/api/v4/projects/37532449/issues/4/notes',
        'Created At (UTC)': '2022-11-17T13:55:11.793Z',
        'Description': 'Neljännen '
                        'testi[liite4.txt](/uploads/461a6b47d039f377903dfc1a5282b731/liite4.txt) '
                        'issuen teksti sisältö jfdfds',
        'Due Date': None,
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/4',
        'GitLab UID': 118915969,
        'Labels': [],
        'Milestone': 'The Best Milestone',
        'Participant EP': 'https://gitlab.com/api/v4/projects/37532449/issues/4/participants',
        'State': 'opened',
        'Time Estimate': 0,
        'Time Spent': 0,
        'Title': 'Neljäs testi issue',
        'URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/4'
    },
    {
        'Assignee': None,
        'Author': 'ilkka.vaisanen@test.com',
        'Closed At (UTC)': None,
        'Comment Link': 'https://gitlab.com/api/v4/projects/37532449/issues/3/notes',
        'Created At (UTC)': '2022-11-16T11:37:57.371Z',
        'Description': 'Kolmannen testi issuen description '
                        '[liite3.txt](/uploads/2bf861ce8317222053be6321f2c89f75/liite3.txt)',
        'Due Date': None,
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/3',
        'GitLab UID': 118824728,
        'Labels': ['Testi_labeli3'],
        'Milestone': 'The Best Milestone',
        'Participant EP': 'https://gitlab.com/api/v4/projects/37532449/issues/3/participants',
        'State': 'opened',
        'Time Estimate': 0,
        'Time Spent': 0,
        'Title': 'Kolmas testi issue',
        'URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/3'
    },
    {
        'Assignee': None,
        'Author': 'ilkka.vaisanen@test.com',
        'Closed At (UTC)': None,
        'Comment Link': 'https://gitlab.com/api/v4/projects/37532449/issues/2/notes',
        'Created At (UTC)': '2022-11-16T11:36:48.251Z',
        'Description': 'Toka testi issue description',
        'Due Date': None,
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/2',
        'GitLab UID': 118824664,
        'Labels': ['Testi_labeli2'],
        'Milestone': 'The Best Milestone',
        'Participant EP': 'https://gitlab.com/api/v4/projects/37532449/issues/2/participants',
        'State': 'opened',
        'Time Estimate': 0,
        'Time Spent': 0,
        'Title': 'Toka Testi Issue',
        'URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/2'
    },
    {
        'Assignee': 'ilkka.vaisanen@test.com',
        'Author': 'ilkka.vaisanen@test.com',
        'Closed At (UTC)': None,
        'Comment Link': 'https://gitlab.com/api/v4/projects/37532449/issues/1/notes',
        'Created At (UTC)': '2022-11-16T11:35:49.326Z',
        'Description': 'Ekan testi issuen description '
                        '[liite1.txt](/uploads/cce591fb40b8f4d26ca36193df2c2c28/liite1.txt)[liite2.txt](/uploads/9a89a909c37c2691db1aece8896708b7/liite2.txt)',
        'Due Date': '2022-11-17',
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/1',
        'GitLab UID': 118824601,
        'Labels': ['Testi_labeli1', 'Testi_labeli2', 'Testi_labeli3'],
        'Milestone': 'The Best Milestone',
        'Participant EP': 'https://gitlab.com/api/v4/projects/37532449/issues/1/participants',
        'State': 'opened',
        'Time Estimate': 0,
        'Time Spent': 0,
        'Title': 'Eka testi issue',
        'URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/1'
    }
]

comment_sample_response = [
    {
        'id': 1021952749,
        'type': None,
        'body': 'MAGNIFICENT TEST COMMENT',
        'attachment': None,
        'author': {
            'id': 11979333,
            'username': 'rjpalt',
            'name': 'Rasmus Paltschik',
            'state': 'active',
            'avatar_url': 'https://secure.gravatar.com/avatar/0c3297d169653dbb9b5658e535e04638?s=80&d=identicon',
            'web_url': 'https://gitlab.com/rjpalt'
        },
        'created_at': '2022-07-11T09:40:48.906Z',
        'updated_at': '2022-07-11T09:40:48.908Z',
        'system': True,
        'noteable_id': 111444664,
        'noteable_type': 'Issue',
        'resolvable': False,
        'confidential': False,
        'internal': False,
        'noteable_iid': 3,
        'commands_changes': {}
    }
]

participants_sample_response = [
    {
        'id': 11979333,
        'username': 'testonen',
        'name': 'Testy Testersson',
        'state': 'active',
        'avatar_url': 'https://secure.gravatar.com/avatar/0c3297d169653dbb9b5658e535e04638?s=80&d=identicon',
        'web_url': 'https://gitlab.com/rjpalt'
    }
]

sample_issue_before_header_formatting = {
    'Title': 'Set up your profile and set your status',
    'Description': '# Set up your profile\n\nSetting up your profile helps others in your team to get to know you better. Things like your name, avatar and your role also make it easier to recognize you when collaborating with others. \n\n* :book:[Read the documentation](https://docs.gitlab.com/ee/user/profile/#profile-settings)\n\n# Set your status\n\nYou can provide a custom status message for your user profile along with an emoji that describes it. This may be helpful when you are out of office or otherwise not available. Other users can then take your status into consideration when responding to your issues or assigning work to you.\n\n* :book:[Read the documentation](https://docs.gitlab.com/ee/user/profile/#current-status)\n\n## Next steps\n\n* [ ] Click on your avatar (in the top right of the main navigation bar), then click **Preferences**.\n* [ ] Choose an emoji and write something to describe your status in the **Current status** section.\n* [ ] Update your personal settings as you wish in the **Main settings** section and click on **Update profile settings** when done.\n\nAll done! :tada: Now others know who you are and what your status is.',
    'GitLab UID': 111095482,
    'GitLab Issue URL': 'https://gitlab.com/rasse-posse/learn-gitlab/-/issues/1',
    'URL': 'https://gitlab.com/rasse-posse/learn-gitlab/-/issues/1',
    'State': 'opened',
    'Author': 'rasmus.paltschik@eficode.com',
    'Assignee': 'rasmus.paltschik@eficode.com',
    'Due Date': None,
    'Created At (UTC)': '2022-07-04T03:40:24.510Z',
    'Closed At (UTC)': None,
    'Labels': ['Novice'],
    'Time Estimate': 0,
    'Time Spent': 0,
    'Milestone': 'The issue was not tied to a milestone',
    'Participant EP': 'https://gitlab.com/api/v4/projects/37532450/issues/1/participants',
    'Comments': [],
    'Participants': ['rasmus.paltschik@eficode.com']
}

sample_fixed_issue_dicts = [
    {
        'Assignee': None,
        'Closed': None,
        'Comments': [],
        'Created': '2022-11-22T13:27:56.554Z',
        'Description': 'issue numero yksi sisältö ja liite '
        '[liite8.txt](/uploads/05a314ad019c8b3592733a5802f6c36a/liite8.txt)',
        'Due Date': None,
        'Epic Link': 'The issue was not tied to a milestone',
        'Estimate': 0,
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/scripting-testing-subgroup/second-scripting-testing-subgroup/scripting-testing-project-in-subgroup/-/issues/1',
        'GitLab UID': 119188120,
        'Labels': [],
        'Reporter': 'ilkka.vaisanen@test.com',
        'Status': 'opened',
        'Summary': 'issue numero yksi',
        'Time Spent': 0,
        'Watchers': ['ilkka.vaisanen@test.com']
    },
    {
        'Assignee': None,
        'Closed': None,
        'Comments': ['2022-11-18T10:00:21.203Z; ilkka.vaisanen@test.com; Neljännen testi issuen neljäs kommentti joka on reply kolmanteen kommenttiin jossa liite 7[liite7.inp](/uploads/4b23613792c5d2b588b92828f7ceb634/liite7.inp)',
                     '2022-11-18T09:58:25.516Z; ilkka.vaisanen@test.com; Neljännen testi issuen kolmas commentti jossa liite5[liite6.zip](/uploads/8ab08652e6d697a525afaa8687d8af1e/liite6.zip)',
                     '2022-11-18T09:13:18.097Z; ilkka.vaisanen@test.com; Neljännen testi issuen commentti jossa liite5[liite5.txt](/uploads/dc9c4ecbe173b5593922ee20bea87a6a/liite5.txt)lisää turhaa tekstiä',
                     '2022-11-18T03:19:37.316Z; rasmus.paltschik@eficode.com; blaa'],
        'Created': '2022-11-17T13:55:11.793Z',
        'Description': 'Neljännen '
        'testi[liite4.txt](/uploads/461a6b47d039f377903dfc1a5282b731/liite4.txt) '
        'issuen teksti sisältö jfdfds',
        'Due Date': None,
        'Epic Link': 'The Best Milestone',
        'Estimate': 0,
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/4',
        'GitLab UID': 118915969,
        'Labels': [],
        'Reporter': 'ilkka.vaisanen@test.com',
        'Status': 'opened',
        'Summary': 'Neljäs testi issue',
        'Time Spent': 0,
        'Watchers': ['rasmus.paltschik@eficode.com', 'ilkka.vaisanen@test.com']
    },
    {
        'Assignee': None,
        'Closed': None,
        'Comments': ['2022-11-17T11:47:07.924Z; rasmus.paltschik@eficode.com; 45',
                     '2022-11-17T11:47:04.862Z; rasmus.paltschik@eficode.com; 44',
                     '2022-11-17T11:47:02.983Z; rasmus.paltschik@eficode.com; 43',
                     '2022-11-17T11:43:53.093Z; rasmus.paltschik@eficode.com; 42',
                     '2022-11-17T11:40:24.849Z; rasmus.paltschik@eficode.com; 41',
                     '2022-11-17T11:40:20.487Z; rasmus.paltschik@eficode.com; 40',
                     '2022-11-17T11:40:17.665Z; rasmus.paltschik@eficode.com; 39',
                     '2022-11-17T11:40:13.176Z; rasmus.paltschik@eficode.com; 38',
                     '2022-11-17T11:40:10.039Z; rasmus.paltschik@eficode.com; 37',
                     '2022-11-17T11:40:07.102Z; rasmus.paltschik@eficode.com; 36',
                     '2022-11-17T11:40:03.492Z; rasmus.paltschik@eficode.com; 35',
                     '2022-11-17T11:40:00.262Z; rasmus.paltschik@eficode.com; 34',
                     '2022-11-17T11:39:57.129Z; rasmus.paltschik@eficode.com; 33',
                     '2022-11-17T11:39:53.965Z; rasmus.paltschik@eficode.com; 32',
                     '2022-11-17T11:39:51.643Z; rasmus.paltschik@eficode.com; 31',
                     '2022-11-17T11:39:48.980Z; rasmus.paltschik@eficode.com; 30',
                     '2022-11-17T11:39:45.795Z; rasmus.paltschik@eficode.com; 29',
                     '2022-11-17T11:39:41.237Z; rasmus.paltschik@eficode.com; 28',
                     '2022-11-17T11:39:38.126Z; rasmus.paltschik@eficode.com; 27',
                     '2022-11-17T11:39:35.660Z; rasmus.paltschik@eficode.com; 26',
                     '2022-11-17T11:39:32.707Z; rasmus.paltschik@eficode.com; 25',
                     '2022-11-17T11:39:29.759Z; rasmus.paltschik@eficode.com; 24',
                     '2022-11-17T11:39:26.915Z; rasmus.paltschik@eficode.com; 23',
                     '2022-11-17T11:39:24.501Z; rasmus.paltschik@eficode.com; 22',
                     '2022-11-17T11:38:16.327Z; rasmus.paltschik@eficode.com; 21',
                     '2022-11-17T11:38:13.438Z; rasmus.paltschik@eficode.com; 20',
                     '2022-11-17T11:38:10.104Z; rasmus.paltschik@eficode.com; 19',
                     '2022-11-17T11:38:06.964Z; rasmus.paltschik@eficode.com; 18',
                     '2022-11-17T11:38:04.160Z; rasmus.paltschik@eficode.com; 17',
                     '2022-11-17T11:38:01.818Z; rasmus.paltschik@eficode.com; 16',
                     '2022-11-17T11:37:59.312Z; rasmus.paltschik@eficode.com; 15',
                     '2022-11-17T11:37:56.443Z; rasmus.paltschik@eficode.com; 14',
                     '2022-11-17T11:37:53.843Z; rasmus.paltschik@eficode.com; 13',
                     '2022-11-17T11:37:51.882Z; rasmus.paltschik@eficode.com; 12',
                     '2022-11-17T11:37:49.309Z; rasmus.paltschik@eficode.com; 11',
                     '2022-11-17T11:37:46.948Z; rasmus.paltschik@eficode.com; 10',
                     '2022-11-17T11:37:43.187Z; rasmus.paltschik@eficode.com; 9',
                     '2022-11-17T11:37:39.722Z; rasmus.paltschik@eficode.com; 8',
                     '2022-11-17T11:37:36.541Z; rasmus.paltschik@eficode.com; 7',
                     '2022-11-17T11:37:33.474Z; rasmus.paltschik@eficode.com; 6',
                     '2022-11-17T11:37:30.441Z; rasmus.paltschik@eficode.com; 5',
                     '2022-11-17T11:37:27.071Z; rasmus.paltschik@eficode.com; 4',
                     '2022-11-17T11:37:24.059Z; rasmus.paltschik@eficode.com; 3',
                     '2022-11-17T11:37:21.299Z; rasmus.paltschik@eficode.com; 2',
                     '2022-11-17T11:37:18.646Z; rasmus.paltschik@eficode.com; 1'],
        'Created': '2022-11-16T11:37:57.371Z',
        'Description': 'Kolmannen testi issuen description '
        '[liite3.txt](/uploads/2bf861ce8317222053be6321f2c89f75/liite3.txt)',
        'Due Date': None,
        'Epic Link': 'The Best Milestone',
        'Estimate': 0,
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/3',
        'GitLab UID': 118824728,
        'Labels': ['Testi_labeli3'],
        'Reporter': 'ilkka.vaisanen@test.com',
        'Status': 'opened',
        'Summary': 'Kolmas testi issue',
        'Time Spent': 0,
        'Watchers': ['rasmus.paltschik@eficode.com', 'ilkka.vaisanen@test.com']
    },
    {
        'Assignee': None,
        'Closed': None,
        'Comments': [],
        'Created': '2022-11-16T11:36:48.251Z',
        'Description': 'Toka testi issue description',
        'Due Date': None,
        'Epic Link': 'The Best Milestone',
        'Estimate': 0,
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/2',
        'GitLab UID': 118824664,
        'Labels': ['Testi_labeli2'],
        'Reporter': 'ilkka.vaisanen@test.com',
        'Status': 'opened',
        'Summary': 'Toka Testi Issue',
        'Time Spent': 0,
        'Watchers': ['ilkka.vaisanen@test.com']
    },
    {
        'Assignee': 'ilkka.vaisanen@test.com',
        'Closed': None,
        'Comments': ['2022-11-16T11:35:49.514Z; ilkka.vaisanen@test.com; assigned to @ivaisanen',
                     '2022-11-16T11:35:49.470Z; ilkka.vaisanen@test.com; changed due date to November 17, 2022'],
        'Created': '2022-11-16T11:35:49.326Z',
        'Description': 'Ekan testi issuen description '
        '[liite1.txt](/uploads/cce591fb40b8f4d26ca36193df2c2c28/liite1.txt)[liite2.txt](/uploads/9a89a909c37c2691db1aece8896708b7/liite2.txt)',
        'Due Date': '2022-11-17',
        'Epic Link': 'The Best Milestone',
        'Estimate': 0,
        'GitLab Issue URL': 'https://gitlab.com/rasse-posse/backend-for-jira/-/issues/1',
        'GitLab UID': 118824601,
        'Labels': ['Testi_labeli1', 'Testi_labeli2', 'Testi_labeli3'],
        'Reporter': 'ilkka.vaisanen@test.com',
        'Status': 'opened',
        'Summary': 'Eka testi issue',
        'Time Spent': 0,
        'Watchers': ['ilkka.vaisanen@test.com']
    }
]
