name: "Issues"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '00 08 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Issue fetcher
        uses: seed-of-apricot/issue-list-readme@v1.1.0
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          pattern: '<!-- issueTable -->'
          labels: 'viikko3'
          state: 'all'
