name: Vulns to Jira

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  create_jira_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Vulns to Jira Action
        uses: EficodeRjpalt/vulns2jira@v0.1.4
        with:
          github_token: ${{ secrets.ADMIN_PAT }}  # Use the PAT instead of GITHUB_TOKEN
          repo: ${{ github.repository }}  # or specify a different repo if needed
