name: "Fetch and Upload GitHub Vulnerabilities"

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: read

jobs:
  github-vulnerability-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch GitHub Vulnerabilities Data (GraphQL)
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
        run: |
          owner=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          name=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          query='
          query ($owner: String!, $name: String!) {
            repository(owner: $owner, name: $name) {
              vulnerabilityAlerts(first: 100) {
                nodes {
                  id
                  createdAt
                  vulnerableManifestPath
                  securityVulnerability {
                    severity
                    package { name ecosystem }
                    advisory {
                      description summary
                      identifiers { value type }
                      references { url }
                      cvss { vectorString }
                    }
                  }
                }
              }
            }
          }'
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               -d "{\"query\": \"$query\", \"variables\": {\"owner\": \"$owner\", \"name\": \"$name\"}}" \
               https://api.github.com/graphql \
               | tee github_vulnerabilities.json


      - name: Display Vulnerabilities
        if: success()
        run: |
          echo "GitHub Vulnerabilities:"
          cat github_vulnerabilities.json
