name: "Fetch and Upload Full GitHub Vulnerabilities Data to DD"

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  FREQUENCY: "yearly"  # Set to "daily", "weekly", "monthly", or "yearly"
  scanType: "Github Vulnerability Scan"
  environment: "Production"

jobs:
  github-vulnerability-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Time Range Based on Frequency
        id: time_range
        run: |
          case "${{ env.FREQUENCY }}" in
            daily)
              since=$(date -u -d '24 hours ago' +"%Y-%m-%dT%H:%M:%SZ")
              ;;
            weekly)
              since=$(date -u -d '7 days ago' +"%Y-%m-%dT%H:%M:%SZ")
              ;;
            monthly)
              since=$(date -u -d '1 month ago' +"%Y-%m-%dT%H:%M:%SZ")
              ;;
            yearly)
              since=$(date -u -d '1 year ago' +"%Y-%m-%dT%H:%M:%SZ")
              ;;
            *)
              echo "Invalid FREQUENCY specified. Choose from daily, weekly, monthly, or yearly."
              exit 1
              ;;
          esac
          echo "Filtering vulnerabilities created since: $since"
          echo "since=$since" >> $GITHUB_ENV  # Save 'since' to the environment file

      - name: Fetch Full GitHub Vulnerabilities Data (GraphQL)
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
        run: |
          owner="${{ github.repository_owner }}"
          name="${{ github.event.repository.name }}"
          query='query ($owner: String!, $name: String!) { repository(owner: $owner, name: $name) { vulnerabilityAlerts(first: 100) { nodes { id createdAt dismissedAt dismisser { login } dismissReason vulnerableManifestFilename vulnerableManifestPath vulnerableRequirements state securityVulnerability { severity updatedAt package { name ecosystem } advisory { description summary identifiers { value type } references { url } cvss { score vectorString } origin publishedAt updatedAt withdrawnAt } firstPatchedVersion { identifier } } } } } }'
          
          json_data="{\"query\": \"$query\", \"variables\": {\"owner\": \"$owner\", \"name\": \"$name\"}}"
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               -d "$json_data" https://api.github.com/graphql \
               -o raw_github_vulnerabilities.json

      - name: Filter Vulnerabilities by Creation Date
        run: |
          since="${{ env.since }}"
          since_unix=$(date -d "$since" +"%s")
          jq --arg since_unix "$since_unix" '
            [
              .data.repository.vulnerabilityAlerts.nodes[]
              | select((.createdAt | fromdateiso8601) > ($since_unix | tonumber))
            ]
          ' raw_github_vulnerabilities.json > github_vulnerabilities.json

      - name: Display Vulnerabilities
        if: success()
        run: |
          echo "GitHub Vulnerabilities:"
          cat github_vulnerabilities.json
  
      - name: Upload Vulnerabilities to Defect Dojo
        env:
          DEFECTDOJO_API_KEY: ${{ secrets.DD_API_KEY }}
          DEFECTDOJO_URL: ${{ secrets.DD_URL }}
          DEFECTDOJO_ENGAGEMENT: ${{ secrets.DD_ENGAGEMENT }}
        run: |
          report="github_vulnerabilities.json"
          ext="json"
          curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DEFECTDOJO_API_KEY" \
            -H "accept: application/json" \
            -H "Content-Type: multipart/form-data" \
            -F "engagement=$DEFECTDOJO_ENGAGEMENT" \
            -F "scan_type=$scanType" \
            -F "test_title=$scanType" \
            -F 'close_old_findings=true' \
            -F 'deduplication_on_engagement=true' \
            -F 'create_finding_groups_for_all_findings=false' \
            -F "environment=$environment" \
            -F "file=@$report;type=application/$ext" \
            -F "branch_tag=$DEFECTDOJO_ENGAGEMENT"

